### ISSUE TITLE
 Detaljniji README.md

### ISSUE THREAD

**Issue by ivan-ristovic** [matf-pp/2020_File-manager#2]
Prvo što će neko videti kad uđe u vaš repozitirijum je README fajl. Dodajte više generalnih informacija o projektu kao i slike/animacije programa u akciji.

**Comment by Hos1g4k1** [comment]
Dodate su animacije koje prikazuju neke od operacija koje se mogu vršiti u aplikaciji kako bi korisnik imao orijentaciono uvid u sam izgled i funkcionisanje aplikacije. Dodat je detaljniji opis samih funkcionalnosti koje aplikacija pruža, kao i načina pokretanja iste i dozvola koje su potrebne da bi pokretanje prošlo nesmetano.
